#! /bin/sh

# check args
if [ "$1" = "-z" ] ; then
    USE_GZIP=1
    shift
fi
SSH_ARGS="$1"
REMOTE_FILE="$2"
if [ ! "$REMOTE_FILE" ] ; then
    echo "Usage: $0 [-z] user@host remote_file [5< prev_digest_file] 6> digest_file > backup_file" >&2
    exit 1
fi
if [ ! -e "/dev/fd/6" ] ; then
    echo "file descriptor 6 (digest output) not open" >&2
    exit 1
fi

# setup variables
if [ ! "$TMPDIR" ] ; then
    TMPDIR="/tmp"
fi
if [ ! "$DUMP_CMD" ] ;then
    DUMP_CMD="blockdiff_dump"
fi
EXIT_CODE=0

# obtain remote TMPDIR
ssh $SSH_ARGS "echo \$TMPDIR" > $TMPDIR/tmpdir.$$ || exit $?
REMOTE_TMPDIR=`cat $TMPDIR/tmpdir.$$`
rm -f $TMPDIR/tmpdir.$$
if [ ! "$REMOTE_TMPDIR" ] ; then
    REMOTE_TMPDIR="/tmp"
fi

# copy digest file to remote
if [ -e "/dev/fd/5" ] ; then
    CMD="cat > $REMOTE_TMPDIR/in_md5.$$"
    if [ "$VERBOSE" ] ; then
	echo "issuing $CMD" >&2
    fi
    ssh $SSH_ARGS "$CMD" <&5 || exit $?
fi

# build and execute blockdiff_dump
CMD="$DUMP_CMD < \"$REMOTE_FILE\" 6> $REMOTE_TMPDIR/out_md5.$$"
if [ -e "/dev/fd/5" ] ; then
    CMD="$CMD 5< $REMOTE_TMPDIR/in_md5.$$"
fi
if [ "$BLOCKSIZE" ] ; then
    CMD="BLOCKSIZE=$BLOCKSIZE $CMD"
fi
if [ "$USE_GZIP" ] ; then
    CMD="$CMD | gzip ; exit \`test \"\${PIPESTATUS[0]}\" -eq 0 -a \"\$?\" -eq 0\`"
fi
if [ "$VERBOSE" ] ; then
    echo "issuing $CMD" >&2
fi    
ssh $SSH_ARGS "$CMD"
EXIT_CODE=$?

# transfer md5
if [ "$EXIT_CODE" -eq 0 ] ; then
    ssh $SSH_ARGS "cat $REMOTE_TMPDIR/out_md5.$$" >&6
    EXIT_CODE=$?
fi

# remove temporary files
ssh $SSH_ARGS "rm -f $REMOTE_TMPDIR/out_md5.$$"
if [ -e "/dev/fd/5" ] ; then
    ssh $SSH_ARGS "rm -f $REMOTE_TMPDIR/in_md5.$$"
fi

exit $EXIT_CODE
